# folder path where all the result will be saved
base_path: /OV-data/JP/results/del
# folder path containing training and validation folder
data_path: /OV-data/JP/BraTS_2020
sample_path: False  # data sample which will be eventualy used in the AG callback

unet:
  build:
    input_shape_: !!python/tuple [128,128,128,3]
    n_depth: 5
    z_depth: ~
    use_attention: False
    use_transconv: True
    normalization: batch
    norm_kwargs: False
    output_probabilities: True
    output_channels: 4
    last_activation: 'softmax'
  fit:
    epochs: 2
    batch_size: 2
    steps_per_epoch: 150
    track_AG: False       # if AG callbacks should be used
    validation_steps: 5